releaseradar/users/routes.py
import flask
import flask_login
import sqlalchemy

import releaseradar
from releaseradar import messages
from releaseradar import models
from releaseradar import radar
from releaseradar.users import forms
from releaseradar.users import utils

users = flask.Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if flask_login.current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        hashed_password = releaseradar.bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = models.User(username=form.username.data,
                           email=form.email.data,
                           password=hashed_password)
        releaseradar.db.session.add(user)
        releaseradar.db.session.commit()
        flask.flash(messages.ACCOUNT_CREATED, 'success')
        return flask.redirect(flask.url_for('users.login'))
    return flask.render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if flask_login.current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))
    form = forms.LoginForm()
    if form.validate_on_submit():
        user = models.User.query.filter_by(email=form.email.data).first()
        if user and releaseradar.bcrypt.check_password_hash(
                user.password, form.password.data):
            flask_login.login_user(user, remember=form.remember.data)
            next_page = flask.request.args.get('next')
            return flask.redirect(next_page) if next_page else flask.redirect(
                flask.url_for('main.home'))
        else:
            flask.flash(messages.LOGIN_FAILED, 'danger')
    return flask.render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    flask_login.logout_user()
    return flask.redirect(flask.url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@flask_login.login_required
def account():
    form = forms.UpdateAccountForm()
    if form.validate_on_submit():
        flask_login.current_user.username = form.username.data
        flask_login.current_user.email = form.email.data
        releaseradar.db.session.commit()
        flask.flash(messages.ACCOUNT_UPDATED, 'success')
        return flask.redirect(flask.url_for('users.account'))
    elif flask.request.method == 'GET':
        form.username.data = flask_login.current_user.username
        form.email.data = flask_login.current_user.email
    return flask.render_template('account.html', form=form)


@users.route("/artists")
@flask_login.login_required
def artists():
    user_artists = flask_login.current_user.artists
    user_artists.sort(key=lambda a: a.name.lower())
    return flask.render_template('artists.html', artists=user_artists)


@users.route("/artist_add", methods=['GET', 'POST'])
@flask_login.login_required
def artist_add():
    form = forms.ArtistAddForm()
    if form.validate_on_submit():
        artist = models.Artist.query.filter(
            sqlalchemy.func.lower(
                models.Artist.name
            ) == sqlalchemy.func.lower(
                form.artist_name.data
            )
        ).first()
        if artist:
            if artist in flask_login.current_user.artists:
                flask.flash(messages.ARTIST_ALREADY_FOLLOWED, 'warning')
                return flask.redirect(flask.url_for('users.artists'))
            flask_login.current_user.artists.append(artist)
            releaseradar.db.session.commit()
            flask.flash(messages.ARTIST_ADDED, 'success')
            return flask.redirect(flask.url_for('users.artists'))
        artist = radar.find_artist(form.artist_name.data)
        if artist:
            releaseradar.db.session.add(artist)
            flask_login.current_user.artists.append(artist)
            releaseradar.db.session.commit()
            flask.flash(messages.ARTIST_ADDED, 'success')
            return flask.redirect(flask.url_for('users.artists'))
        flask.flash(messages.ARTIST_NOT_FOUND, 'warning')
        return flask.redirect(flask.url_for('users.artist_add'))
    return flask.render_template('artist_add.html', form=form)


@users.route("/artist_remove/<artist_id>", methods=['POST'])
@flask_login.login_required
def artist_remove(artist_id):
    flask_login.current_user.artists.remove(
        models.Artist.query.get_or_404(artist_id)
    )
    releaseradar.db.session.commit()
    flask.flash(messages.ARTIST_REMOVED, 'success')
    return flask.redirect(flask.url_for('users.artists'))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if flask_login.current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))
    form = forms.RequestResetForm()
    if form.validate_on_submit():
        user = models.User.query.filter_by(email=form.email.data).first()
        utils.send_reset_email(user)
        msg = messages.RESET_PASSWORD_EMAIL_SENT
        flask.flash(msg, 'info')
        return flask.redirect(flask.url_for('users.login'))
    return flask.render_template('reset_request.html',
                                 title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if flask_login.current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))
    user = models.User.verify_reset_token(token)
    if user is None:
        flask.flash(messages.TOKEN_INVALID, 'warning')
        return flask.redirect(flask.url_for('users.reset_request'))
    form = forms.ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = releaseradar.bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        releaseradar.db.session.commit()
        flask.flash(messages.PASSWORD_UPDATED, 'success')
        return flask.redirect(flask.url_for('users.login'))
    return flask.render_template('reset_token.html',
                                 title='Reset Password',
                                 form=form)

releaseradar/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Account Info</legend>
      <div class="form-group">
        {{ form.username.label(class="form-control-label") }}
        {% if form.username.errors %}
        {{ form.username(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.username(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
        {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

releaseradar/templates/artist_add.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Add a new artists</legend>
      <div class="form-group">
        {{ form.artist_name.label(class="form-control-label") }}
        {{ form.artist_name(class="form-control form-control-lg") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

releaseradar/templates/artists.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
  <legend class="border-bottom mb-4">My Artists | <a href="{{ url_for('users.artist_add') }}">Add a new artist</a>
  </legend>
  {% if artists %}
  <ul>
    {% for artist in artists %}
    <li>
      <a href="{{artist.spotify_url}}" target="_blank">{{artist.name}}</a>
      <a href="#" class="text-danger" data-toggle="modal" data-target="#deleteModal"
         data-remove-url="{{url_for('users.artist_remove', artist_id=artist.id)}}">Remove</a>
    </li>
    {% endfor %}
  </ul>
  {% endif %}
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Remove this artist?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form id="deleteForm" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#deleteModal').on('show.bs.modal', function (e) {
            let removeUrl = $(e.relatedTarget).data('remove-url');
            $("#deleteForm").attr('action', removeUrl);
        });
    });
</script>
{% endblock content %}

releaseradar/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <title>Release Radar</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"></script>
</head>
<body>
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="/"><b>Release Radar</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
              aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
        </div>
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" href="{{ url_for('users.artists') }}">My Artists</a>
          <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
          <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
          {% else %}
          <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
          <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>
<main role="main" class="container">
  <div class="row">
    <div class="col-md-12">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      {% block content %}{% endblock %}
    </div>
  </div>
</main>
</body>
</html>

releaseradar/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="text-center">
  <h1>Release Radar</h1>
  <h3>Release Radar notifies you when your favorite artists release new albums</h3>
  <h6>How does it work?</h6>
  <p>You register an account and pick which artists you want to follow. When any of your chosen artists release a new
    album, we notify you by email. We will never spam you or share your email to any third parties.</p>
  <div class="row">
    <div class="col-md-6">
      <div class="content-section">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Register Now</a>
      </div>
    </div>
    <div class="col-md-6">
      <div class="content-section">
        Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Log In</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

releaseradar/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log In</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
        {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class="form-check-input") }}
        {{ form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
      <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
      </small>
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
  </small>
</div>
{% endblock content %}

releaseradar/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Join Today</legend>
      <div class="form-group">
        {{ form.username.label(class="form-control-label") }}
        {% if form.username.errors %}
        {{ form.username(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.username(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
        {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.confirm_password.label(class="form-control-label") }}
        {% if form.confirm_password.errors %}
        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.confirm_password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
  </small>
</div>
{% endblock content %}

releaseradar/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
        {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

releaseradar/templates/reset_token.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.confirm_password.label(class="form-control-label") }}
        {% if form.confirm_password.errors %}
        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.confirm_password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}